import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Brain, Target, TrendingUp } from "lucide-react";
import "./Home.css";


function Home() {

  return (

    <div className="home">

      <section className="hero">

        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >

          <h1>
            TalentOS
          </h1>


          <h2>
            Your personal AI-powered interview coach
          </h2>


          <p>
            Generate personalized interviews,
            analyze your performance,
            and improve your weak skills.
          </p>


          <Link to="/login">
            <button>
              Start Free Interview
            </button>
          </Link>


        </motion.div>

      </section>



      <section className="features">


        <motion.div
          className="feature-card"
          whileHover={{ scale: 1.05 }}
        >

          <Brain size={40}/>

          <h3>
            AI Generated Interviews
          </h3>

          <p>
            Practice realistic interview questions generated by AI.
          </p>

        </motion.div>



        <motion.div
          className="feature-card"
          whileHover={{ scale: 1.05 }}
        >

          <Target size={40}/>

          <h3>
            Performance Analysis
          </h3>

          <p>
            Get feedback and improve your answers.
          </p>

        </motion.div>



        <motion.div
          className="feature-card"
          whileHover={{ scale: 1.05 }}
        >

          <TrendingUp size={40}/>

          <h3>
            Skill Improvement
          </h3>

          <p>
            Find weak areas and improve faster.
          </p>

        </motion.div>


      </section>


    </div>

  );

}


export default Home;